### ISSUE TITLE
Requesting adjustment to plate.py

### ISSUE THREAD

**Issue by Woovie** [ahtn/keyboard_case_and_pcb_gen#1]
Hello,

I would like to propose the following change:
[plate_patch.txt](https://github.com/ahtn/keyboard_case_and_pcb_gen/files/1878484/plate_patch.txt)

--- plate.py	2018-04-04 22:29:29.000000000 -0500
+++ plate3.py	2018-04-04 22:29:53.000000000 -0500
@@ -1,4 +1,4 @@
-#!/usr/bin/env python
+#!/usr/bin/env python3

In most environments I work in (Redhat, OSX w/ brew) this would ensure that Python 3 is used for execution instead.

Thank you

**Comment by ahtn** [comment]
Fixed bccafda1b1c9b986fab10b1cfec27f11f612dc10
